<a href="https://colab.research.google.com/github/Debdeep-Goswami/Python3/blob/main/PythonBasicDataTypes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Simple data types and operators

In [ ]:
name='iphone 5s'

In [ ]:
type(name)

str

In [ ]:
print(name)

iphone 5s


In [ ]:
screen_size=4.3
type(screen_size)

float

In [ ]:
number_of_speakers = 1
type(number_of_speakers)

int

In [ ]:
print('I just bought an '+name)

I just bought an iphone 5s


In [ ]:
a=3
b=2
print(a*b,a/b,a+b,a-b,a//b,a**b)

6 1.5 5 1 1 9


In [ ]:
is_android=False
type(is_android)

bool

In [ ]:
print(is_android==False, is_android==True)

True False


In [ ]:
if is_android==False:
  print(name+' doesnot support android.')
  print('continue to print inside if block')
print("Printing out of if block")

iphone 5s doesnot support android.
continue to print inside if block
Printing out of if block


#Loops and Function

In [ ]:
for i in range(5):
  print (i,i**2)

0 0
1 1
2 4
3 9
4 16


In [ ]:
range?

In [ ]:
i=0
while i<5:
  print(i,i**2)
  i+=1  # equivalent to i=i+1

0 0
1 1
2 4
3 9
4 16


In [ ]:
def print_squares(stop_val):
  for i in range(stop_val):
    print(i,i**2)

print_squares(10)

0 0
1 1
2 4
3 9
4 16
5 25
6 36
7 49
8 64
9 81


In [ ]:
def sum_of_squares(stop_val):
  sum=0
  for i in range(stop_val):
    sum+=i**2
  return sum

sum_of_squares(10)

285

In [ ]:
print_square(10)
sum_of_squares(10)

0 0
1 1
2 4
3 9
4 16
5 25
6 36
7 49
8 64
9 81


285

In [ ]:
sum=sum_of_squares(10)
print('Sum of all squares',sum)

Sum of all squares 285


In [ ]:
help(range)

In [ ]:
for i in range(1,10):
  print(i,i**2)

1 1
2 4
3 9
4 16
5 25
6 36
7 49
8 64
9 81


# Lists


In [ ]:
my_phone = [name, is_android, screen_size]
type(my_phone)

list

In [ ]:
print(my_phone)

['iphone 5s', False, 4.3]


In [ ]:
my_dads_phone=my_phone
print(my_dads_phone)

['iphone 5s', False, 4.3]


In [ ]:
my_phone[2]=4

In [ ]:
print(my_phone)
print(my_dads_phone)

In [ ]:
my_dads_phone=list(my_phone)
# this is called deep copy where both the copies ae independent to each other
my_phone[2]=6



In [ ]:
print(my_phone)
print(my_dads_phone)

['iphone 5s', False, 6, '3G']
['iphone 5s', False, 6]


In [ ]:
my_phone.append('3G')

In [ ]:
my_phone_specs=['single sim',50000]

In [ ]:
print(my_phone_specs)

['single sim', 50000]


In [ ]:
my_phone=my_phone+my_phone_specs

In [ ]:
print(my_phone)

['iphone 5s', False, 6, '3G', 'single sim', 50000]


In [ ]:
b=list(range(5))
c= list(map(lambda x: x**2,b))
print(c)

[0, 1, 4, 9, 16]


# Tuple

In [ ]:
my_phone_tupple=('iPhone-5s','False','50000','5')
print(my_phone_tupple)

('iPhone-5s', 'False', '50000', '5')


In [ ]:
my_phone_tupple[2]=4

TypeError: ignored

In [ ]:
import time
tic=time.time()
print(tic)

1606189065.6983893


In [ ]:
toc=time.time()
print('Time difference in seconds ',toc-tic)

Time difference in seconds  64.66570925712585


# Sets


In [ ]:
my_set=('Debdeep','M.Tech','30')
print(my_set)

('Debdeep', 'M.Tech', '30')


In [ ]:
print(my_set.count)

<built-in method count of tuple object at 0x7f1cf183bc60>


In [ ]:
my_set.index('30')

2

In [ ]:
my_set.count('30')

1

# Dictionary

In [ ]:
my_phone_dict={}
type(my_phone_dict)

dict

In [ ]:
my_phone_dict={
    'name':'iPhone-5s',
    'is_android':False,
    'price':50000,
    'screen_size':5.5,
    'other':['It is superb','Debdeep is the owner']
}

print(my_phone_dict)

{'name': 'iPhone-5s', 'is_android': False, 'price': 50000, 'screen_size': 5.5, 'other': ['It is superb', 'Debdeep is the owner']}


In [ ]:
my_phone_dict['value_for_money']=True

In [ ]:
print(my_phone_dict)

{'name': 'iPhone-5s', 'is_android': False, 'price': 50000, 'screen_size': 5.5, 'other': ['It is superb', 'Debdeep is the owner'], 'value_for_money': True}


In [ ]:
my_phone_dict['other']

['It is superb', 'Debdeep is the owner']

In [ ]:
my_phone_dict.keys()

dict_items([('name', 'iPhone-5s'), ('is_android', False), ('price', 50000), ('screen_size', 5.5), ('other', ['It is superb', 'Debdeep is the owner']), ('value_for_money', True)])

In [ ]:
my_phone_dict.items()

dict_items([('name', 'iPhone-5s'), ('is_android', False), ('price', 50000), ('screen_size', 5.5), ('other', ['It is superb', 'Debdeep is the owner']), ('value_for_money', True)])

In [ ]:
my_phone_dict.values()

dict_values(['iPhone-5s', False, 50000, 5.5, ['It is superb', 'Debdeep is the owner'], True])

In [ ]:
for key in my_phone_dict.keys():
  print(key,' = ',my_phone_dict[key])

name  =  iPhone-5s
is_android  =  False
price  =  50000
screen_size  =  5.5
other  =  ['It is superb', 'Debdeep is the owner']
value_for_money  =  True


# Python Packages

In [ ]:
import math
a=math.sqrt(100)
print(a)
print(math.sqrt(1000))

10.0
31.622776601683793


In [ ]:
print(math.pow(2,10))

1024.0


In [ ]:
import math as m
print(m.factorial(10))

3628800


In [ ]:
from math import factorial
print(factorial(5))

120


# User defined Package

In [ ]:
!touch my_first_module.py

In [ ]:
!echo '# this is my own module' >> my_first_module.py

In [ ]:
!cat my_first_module.py


# this is my own module


In [ ]:
!echo '# this is my own module'>my_first_module.py
!echo 'def display():' >>my_first_module.py
!echo '    print("This is created by Debdeep")'>>my_first_module.py

In [ ]:
!cat my_first_module.py

# this is my own module
def display():
    print("This is created by Debdeep")


In [ ]:
import my_first_module as mfm
mfm.display()

This is created by Debdeep


In [ ]:
from my_first_module import display
display()

This is created by Debdeep


In [ ]:
from my_first_module import display as output
output()

This is created by Debdeep


# **File Handling**

In [1]:
!ls 

sample_data


In [3]:
!ls

sample_data  Test.txt


In [4]:
file=open('Test.txt','r')
s=file.readline()
print(s)

I am Debdeep	Dev



In [5]:
print(s.split('\t'))

['I am Debdeep', 'Dev\n']


In [8]:
print(s.split(' '))

['I', 'am', 'Debdeep\tDev\n']


In [9]:
file.close()

In [10]:
print(file.readline())

ValueError: ignored

In [11]:
with open('Test.txt','r') as file:
  print(file.readlines())

['I am Debdeep\tDev\n', 'Yu are \tSunny']


In [12]:
file.readline()

ValueError: ignored

In [13]:
with open('Test.txt','r') as file:
  print(file.read())

I am Debdeep	Dev
Yu are 	Sunny


In [14]:
with open('Test.txt','r') as file:
  for line in file:
    print(line)

I am Debdeep	Dev

Yu are 	Sunny


File Wriiting

In [33]:
file=open('Test_write.txt','w')
file.write('Hi this is written from the program')

35

In [34]:
!cat Test_write.txt

Hi this is written from the program

In [35]:
file=open('Test_write.txt','a')
file.write('\nHi this is another line written from the program')

49

In [36]:
!cat Test_write.txt

Hi this is written from the program

In [37]:
file.close()

In [38]:
!python --version

Python 3.6.9


#**Class in Python**

In [64]:
class MobilePhone:
  def __init__(self):
    print('Object creation is successful')

  def __init__(self,name):
    self.name=name
    print(name)
    print(self.name)
    name="You"
    print(name)
    print(self.name)

  def __init__(self,name,price):
    self.name=name
    self.price=price
    print(self.name)
    print(self.price)


In [65]:
new_phone=MobilePhone()

TypeError: ignored

In [55]:
type(new_phone)

__main__.MobilePhone

In [66]:
new_phone2=MobilePhone("iPhone 6s")

TypeError: ignored

#**NumPy**

In [67]:
import numpy as np

In [68]:
x=np.array([1,2,3])

In [69]:
print(x)

[1 2 3]


In [70]:
type(x)

numpy.ndarray

In [71]:
x[2]=10
print(x)

[ 1  2 10]


In [72]:
x[5]=100

IndexError: ignored

In [77]:
l=[1,2,3]
type(l)

list

In [78]:
x=np.asarray(l)
type(x)

numpy.ndarray

In [80]:
x=np.asarray(l,float)
type(x)

numpy.ndarray

In [81]:
print(x)

[1. 2. 3.]


In [82]:
x=np.array([[1,2,3],[3,4,5]])

In [83]:
print(x)

[[1 2 3]
 [3 4 5]]


In [84]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [85]:
x.shape

(3, 3)

In [88]:
x=np.zeros((3,4))

In [89]:
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [91]:
x=np.eye(3,3)

In [92]:
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [93]:
x=np.random.random((4,5))
print(x)

[[0.53275416 0.75365784 0.62637924 0.39074473 0.25441645]
 [0.63998507 0.54537869 0.66929157 0.15731624 0.92050728]
 [0.24573407 0.10124125 0.25284414 0.9212782  0.48749532]
 [0.61275625 0.59704281 0.90144478 0.95804898 0.40335242]]


In [97]:
z=x.T
print('x =\n',x)
print('z =\n',z)

x =
 [[27.54161581 36.57837744 63.79239913  7.44725159 44.16453802]
 [99.85068282 53.78685011 92.91566503 73.16238377  5.07276093]
 [57.34068926 12.4125063  28.4413966  12.78197502 74.95321847]
 [27.56254448 70.42814261 14.44777347 80.48984855 33.52415291]]
z =
 [[27.54161581 99.85068282 57.34068926 27.56254448]
 [36.57837744 53.78685011 12.4125063  70.42814261]
 [63.79239913 92.91566503 28.4413966  14.44777347]
 [ 7.44725159 73.16238377 12.78197502 80.48984855]
 [44.16453802  5.07276093 74.95321847 33.52415291]]


In [100]:
y=x.reshape(20,1)

In [101]:
print(y)

[[27.54161581]
 [36.57837744]
 [63.79239913]
 [ 7.44725159]
 [44.16453802]
 [99.85068282]
 [53.78685011]
 [92.91566503]
 [73.16238377]
 [ 5.07276093]
 [57.34068926]
 [12.4125063 ]
 [28.4413966 ]
 [12.78197502]
 [74.95321847]
 [27.56254448]
 [70.42814261]
 [14.44777347]
 [80.48984855]
 [33.52415291]]
